env: development

server:
  port: 9000

spring:
  thymeleaf:
    cache: false
  datasource:
    youyou:
      jdbc-url: jdbc:mysql://localhost:3306/youyou?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    jedis:
      pool:
        max-active: 50
        min-idle: 5
        max-wait: 3000
        max-idle: 20
    host: 127.0.0.1
    password: test
    port: 6379
    database: 0
    timeout: 3000

